In [ ]:
print(1+1)

2


In [3]:
import numpy as np

In [ ]:
print(np.array([1,2,3]))

[1 2 3]


In [ ]:
print([1, 2, 3]*2)

[1, 2, 3, 1, 2, 3]


In [ ]:
arr_1 = np.array([1, 2, 3])
print(arr_1 * 2)

[2 4 6]


In [ ]:
arr_2 = np.array(
    [
        [1, 2, 3], [4, 5, 6], [7, 8, 9]
    ]
)

print(arr_2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(np.array([1, 2, 3]).dtype)

int64


In [ ]:
print(np.array([1, 2, 3], dtype='int8') .dtype)

int8


In [ ]:
list_1 = [1, 2, 3]
list_2 = [4, 5, 6]
print(list_1 + list_2)

result = [x + y for x, y in zip(list_1, list_2)]
print(result)

[1, 2, 3, 4, 5, 6]
[5, 7, 9]


In [ ]:
ndarr_1 = np.array([1, 2, 3])
ndarr_2 = np.array([4, 5, 6])
print(ndarr_1 + ndarr_2)

[5 7 9]


In [ ]:
# a = np.arange(12)
# 1~11까지의 1차원배열이 만들어짐
a =  np.arange(12).reshape(3, 4) #reshape로 변환
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
print(a.shape) #배열의 각 축(axis)의 크기
print(a.ndim) #축의 개수
print(a.dtype) #각 요소의 데이터 타입
print(a.itemsize) # 각 요소 타입의 byte크기
print(a.size) #전체 요소의 개수

(3, 4)
2
int64
8
12


In [ ]:
print(np.zeros((3,4), dtype=int))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
print(np.ones((3,4), dtype=int))

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [ ]:
print(np.empty((3,4)))

[[5.e-324 5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324 5.e-324]]


In [ ]:
print(np.arange(10, 30, 5))
print(np.arange(1, 31, 3))

[10 15 20 25]
[ 1  4  7 10 13 16 19 22 25 28]


In [ ]:
print(np.linspace(start=1, stop=10, num=5, dtype=int))

[ 1  3  5  7 10]


In [ ]:
A = np.array(
    [
        [1, 1],
        [0, 1]
    ]
)

B = np.array(
    [
        [2,0],
        [3,4]
    ]
)

print(A * B) #행렬 곱셈이 아님
print(A @ B)

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]


In [ ]:
A = np.array([1, 2, 3, 4])
B = np.array([1, 1, 3, 3])

print(A > B)

[False  True False  True]


In [ ]:
a = np.arange(8).reshape(2, 4) **2
print(a)

[[ 0  1  4  9]
 [16 25 36 49]]


In [ ]:
print(a.sum())
print(a.mean())
print(a.max())
print(a.min())
print(a.cumsum()) # 누적된 합
print(a.argmax()) # 최댓값의 인덱스

140
17.5
49
0
[  0   1   5  14  30  55  91 140]
7


In [ ]:
a = np.arange(8).reshape(2, 4) **2
print(a)

print(a.mean(axis=0))
print(a.mean(axis=1))

[[ 0  1  4  9]
 [16 25 36 49]]
[ 8. 13. 20. 29.]
[ 3.5 31.5]


In [ ]:
a = np.array([0, 1, 2, 3, 4, 5])
print(a[0])
print(a[4])
print(a[1:3])

0
4
[1 2]


In [ ]:
# 2차원 배열 3행 4열의 데이터를 생성 후 : 0 ~ 11
# a > 4조건 값만 출력하시오.

a = np.arange(12).reshape(3, 4)
# print(a > 4)
b = a > 4
print(a[b])
print(a[b].shape)
print(a)

[ 5  6  7  8  9 10 11]
(7,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
a[b] = 1000
print(a)

[[   0    1    2    3]
 [   4 1000 1000 1000]
 [1000 1000 1000 1000]]


In [ ]:
a = np.array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'])
print(a)

['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h']


In [ ]:
#b, b, d, e
i = np.array([1, 1, 3, 4])

print(a[i])

['b' 'b' 'd' 'e']


In [ ]:
#[['d', 'e'],['f', 'g'] ]

j = np.array([[3,4],[5,6]])

print(a[j])


[['d' 'e']
 ['f' 'g']]


In [ ]:
b = np.array(['a', 'b', 'c', 'd'])

k = np.array([3, 2, 1, 0])
print(b[k])

['d' 'c' 'b' 'a']


In [ ]:
a = np.arange(12).reshape(3,4)
print(a)
print(a.shape)
print(a.ndim)

b = a.reshape(2,6)
print(b.shape)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
2
(2, 6)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [ ]:
c = a.reshape(-1, 3)
#-1 => 난 계산 안되 알아서 해줘
print(c)
print(c.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(4, 3)


In [ ]:
a = np.arange(12).reshape(3,4)

print(a.ravel())
print(a.reshape(-1))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
b = a.T
print(b)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [ ]:
a = np.array([1, 2, 3, 4]).reshape(2,2)
b = np.array([5, 6, 7, 8]).reshape(2,2)

print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [ ]:
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
a = np.arange(12).reshape(2,6)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [ ]:
print(np.vsplit(a,2))
print(np.hsplit(a,3))

[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]])]
[array([[0, 1],
       [6, 7]]), array([[2, 3],
       [8, 9]]), array([[ 4,  5],
       [10, 11]])]


In [9]:
customer = np.array(
    [
        [150, 25, 0],
        [200, 30, 0],
        [50, 10, 1],
        [300, 45, 0]
    ]
)
print(customer)

[[150  25   0]
 [200  30   0]
 [ 50  10   1]
 [300  45   0]]


In [10]:
new_customer = np.array(
    [
     [120, 20, 0],
     [180, 35, 1],
     [75, 5, 0],
     [160, 25, 0]
    ]
)
print(new_customer)

[[120  20   0]
 [180  35   1]
 [ 75   5   0]
 [160  25   0]]


In [11]:
combined_data = np.vstack((customer, new_customer))
print(combined_data)

[[150  25   0]
 [200  30   0]
 [ 50  10   1]
 [300  45   0]
 [120  20   0]
 [180  35   1]
 [ 75   5   0]
 [160  25   0]]


In [12]:
# print(combined_data.sum(axis=1))
# print(combined_data.sum(axis=0)[0])
total_comment_length = combined_data.sum(axis=0)[0]
total_likes = combined_data.sum(axis=0)[1]
average_comment_lenght = combined_data.mean(axis=0)[0]
average_likes = combined_data.mean(axis=0)[1]
print(total_comment_length)
print(total_likes)
print(average_likes)


1235
195
24.375


In [13]:
divided_data = np.vsplit(combined_data, 4)
print(divided_data)

[array([[150,  25,   0],
       [200,  30,   0]]), array([[ 50,  10,   1],
       [300,  45,   0]]), array([[120,  20,   0],
       [180,  35,   1]]), array([[ 75,   5,   0],
       [160,  25,   0]])]


In [ ]:
column_sums = combined_data.sum(axis=0)
total_comment_length = column_sums[0]
total_likes = column_sums[1]
column_means = combined_data.mean(axis=0)
average_comment_length = column_means[0]
average_likes = column_means[1]

print("댓글 길이 총합: " , total_comment_length)
print("좋아요 수 총합: " , total_likes)
print("댓글 길이 평균: " , average_comment_length)
print("댓글 길이 평균: " , average_comment_length)

댓글 길이 총합:  1235
좋아요 수 총합:  195
댓글 길이 평균:  154.375
댓글 길이 평균:  154.375


In [ ]:
selected_customers = combined_data[[0, 2, 4], :]
print(selected_customers)

[[150  25   0]
 [ 50  10   1]
 [120  20   0]]


In [7]:
t = combined_data.T
print(t)

NameError: name 'combined_data' is not defined

In [6]:
new_customers = np.zeros((2,3), dtype=int)
print(new_customers)

[[0 0 0]
 [0 0 0]]


In [14]:
combined_data[:, 1] = combined_data[:, 1] + 10
         # 두 번째 열
print(combined_data)

[[150  35   0]
 [200  40   0]
 [ 50  20   1]
 [300  55   0]
 [120  30   0]
 [180  45   1]
 [ 75  15   0]
 [160  35   0]]


In [17]:
np.random.seed(0)
scores = np.random.randint(0, 101, size=(10,5))
print(scores)

[[44 47 64 67 67]
 [ 9 83 21 36 87]
 [70 88 88 12 58]
 [65 39 87 46 88]
 [81 37 25 77 72]
 [ 9 20 80 69 79]
 [47 64 82 99 88]
 [49 29 19 19 14]
 [39 32 65  9 57]
 [32 31 74 23 35]]


In [19]:
student_sum = scores.sum(axis=1)
student_mean = scores.mean(axis=1)
print(student_sum)
print(student_mean)

[289 236 316 325 292 257 380 130 202 195]
[57.8 47.2 63.2 65.  58.4 51.4 76.  26.  40.4 39. ]


In [20]:
sbjt_sum = scores.sum(axis=0)
sbjt_mean = scores.mean(axis=0)
print(sbjt_sum)
print(sbjt_mean)

[445 470 605 457 645]
[44.5 47.  60.5 45.7 64.5]


In [26]:
first_sum = student_sum.max()
first_mean = student_mean.max()
print("1등 학생의 총점은 ", first_sum, "평균은 ", first_mean)

1등 학생의 총점은  380 평균은  76.0


In [22]:
upper_60 = student_mean[student_mean >= 60]
print(upper_60)

[63.2 65.  76. ]


In [23]:
for i, mean_score in enumerate(student_mean):
    if mean_score >= 60:
        each_scores = scores[i]  # 해당 학생의 각 과목 점수
        print(f"학생 {i+1}: 각 점수 {each_scores}, 평균 {mean_score:.1f}")

학생 3: 각 점수 [70 88 88 12 58], 평균 63.2
학생 4: 각 점수 [65 39 87 46 88], 평균 65.0
학생 7: 각 점수 [47 64 82 99 88], 평균 76.0


In [24]:
max_avg = sbjt_mean.max()
max_sum = sbjt_sum.max()
max_index = sbjt_mean.argmax()


print(f"평균이 가장 높은 과목: {max_index+1}번째 과목")
print(f"해당 과목의 평균: {max_avg:.1f}")
print(f"해당 과목의 총점 : {max_sum:.1f}")
print(f"해당 과목의 모든 학생 점수: {scores[:, max_index]}")

평균이 가장 높은 과목: 5번째 과목
해당 과목의 평균: 64.5
해당 과목의 총점 : 645.0
해당 과목의 모든 학생 점수: [67 87 58 88 72 79 88 14 57 35]


In [25]:
high_avg_mask = student_avg >=60
high_avg_scores = scores[high_avg_mask]
high_avg_values = student_avg[high_avg_mask]

print("전체 성적표 : \n", scores)
print("학생별 평균 점수  : \n", np.round(student_avg, 2))

if high_avg_scores.shape[0] > 0:
  count = 1
  for score, avg in aip(high_avg_scores, high_avg_values):
    print(f"학생 {count}: 점수 = {score}, 평균 = {round(avg, 2)}")
    count +=1
else:
  print("해당 학생이 없습니다. ")

NameError: name 'student_avg' is not defined

In [35]:
selected_customers_2 = combined_data[(combined_data[:, 0]>=100)
                                      & (combined_data[:, 1]>=20)
                                      & (combined_data[:, 2] == 0)]
print(selected_customers_2)

[[150  35   0]
 [200  40   0]
 [300  55   0]
 [120  30   0]
 [160  35   0]]
